# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OkXCiQHK_HTVDOpBwBShcwfN6wMRvVJt
"""

def days_until_launch(current_day, launch_day):
    """"Returns the days left before launch.
    
    current_day - current day in integer
    launch_day (int) - launch day in integer
    """
    if launch_day >= current_day:
	    day = launch_day - current_day
    else:
	    day = 0 
    return day